enabled = true
title = "CSSE"

[quickstart]
enabled = true
active_file = ""
load_cell = true
position = [ 0.0, 0.0, 0.0,]
data_files = []
orientation = [ 0.0, 0.0, 0.0,]
cell = ""

[dialogue_window]
highlight_modified_items = true

[object_window]
clear_filter_on_tab_switch = true
filter_by_book_text = true
filter_by_script_id = true
filter_by_model_path = true
filter_by_icon_path = true
filter_by_id = true
filter_by_name = true
filter_by_enchantment_id = true
highlight_modified_items = true
case_sensitive = false
use_regex = false

[script_editor]
font_face = "Consolas"
font_size = 10

[render_window]
fov = 53.130104
use_legacy_object_movement = false
multisamples = 0
use_world_axis_rotations_by_default = true
use_group_scaling = false
use_legacy_grid_snap = true

[object_window.column_light_time]
width = 45

[object_window.column_script]
width = 100

[object_window.column_book_teaches]
width = 100

[object_window.column_name]
width = 190

[object_window.column_actor_respawns]
width = 45

[object_window.column_creature_bipedal]
width = 45

[object_window.column_weapon_silver]
width = 45

[object_window.column_weapon_reach]
width = 45

[object_window.column_actor_item_list]
width = 100

[object_window.column_weapon_ignores_resistance]
width = 45

[object_window.column_actor_class]
width = 100

[object_window.column_animation]
width = 100

[object_window.column_actor_essential]
width = 45

[object_window.column_playable]
width = 45

[object_window.column_actor_faction]
width = 100

[object_window.column_actor_faction_rank]
width = 100

[object_window.column_type]
width = 100

[object_window.column_actor_level]
width = 45

[object_window.column_all_lte_pc]
width = 45

[object_window.column_book_is_scroll]
width = 45

[object_window.column_autocalc]
width = 45

[object_window.column_creature_use_weapon_and_shield]
width = 45

[object_window.column_creature_movement_type]
width = 100

[object_window.column_blocked]
width = 45

[object_window.column_charge]
width = 45

[object_window.column_race]
width = 100

[object_window.column_cost]
width = 45

[object_window.column_modified]
width = 45

[object_window.column_count]
width = 45

[object_window.column_id]
width = 374

[object_window.column_creature_sound]
width = 100

[object_window.column_quality]
width = 45

[object_window.column_effect]
width = 100

[object_window.column_enchanting]
width = 100

[object_window.column_enchantment]
width = 45

[object_window.column_female]
width = 45

[object_window.column_health]
width = 45

[object_window.column_inventory]
width = 100

[object_window.column_leveled_creature_list]
width = 100

[object_window.column_leveled_item_list]
width = 100

[object_window.column_sound]
width = 100

[object_window.column_light_radius]
width = 45

[object_window.column_model]
width = 217

[object_window.column_persists]
width = 45

[object_window.column_organic]
width = 45

[object_window.column_part]
width = 100

[object_window.column_part_type]
width = 100

[object_window.column_spell_pc_start]
width = 45

[object_window.column_rating]
width = 45

[object_window.column_uses]
width = 45

[object_window.column_value]
width = 45

[object_window.column_weapon_chop_max]
width = 45

[object_window.column_weapon_chop_min]
width = 45

[object_window.column_weapon_slash_max]
width = 45

[object_window.column_weapon_slash_min]
width = 45

[object_window.column_weapon_speed]
width = 45

[object_window.column_weapon_thrust_max]
width = 45

[object_window.column_weapon_thrust_min]
width = 45

[object_window.column_weight]
width = 45

[object_window.column_weight_class]
width = 45
